from django.urls import path

from . import views

urlpatterns = [
    path("health/", views.health, name="health"),
    path("info/", views.info, name="info"),
    path("stocks/", views.stocks_list, name="stocks_list"),
    path("stock/<str:ide>/fdk/", views.stock_fdk, name="stock_fdk"),
    path("stock/<str:ide>/indicators/", views.stock_indicators_view, name="stock_indicators"),
    path("stock/<str:ide>/swings/", views.stock_swings_view, name="stock_swings"),
    path("stock/<str:ide>/fsa/", views.stock_fsa, name="stock_fsa"),
    path("stock/<str:ide>/main-fsa/", views.stock_main_fsa, name="stock_main_fsa"),
    path("stock/<str:ide>/reports/", views.stock_reports, name="stock_reports"),
    path("stock/<str:ide>/cw/", views.stock_cw_tables, name="stock_cw_tables"),
    path("stock/<str:ide>/cw/<str:name>/", views.stock_cw, name="stock_cw"),
    path("stock/<str:ide>/", views.stock_info, name="stock_info"),
    path("stock/<str:ide>/ratio/<str:name>/", views.stock_ratio, name="stock_ratio"),
    path("hy/list/", views.hy_list, name="hy_list"),
    path("hy/", views.hy_sectors, name="hy_sectors"),
    path("hy/<str:ids>/stocks/", views.hy_stocks, name="hy_stocks"),
    path("hy/<str:ids>/", views.hy_info, name="hy_info"),
    path("market/heatmap/", views.market_heatmap, name="market_heatmap"),
    path(
        "industry/profit-growth/",
        views.industry_profit_growth,
        name="industry_profit_growth",
    ),
    path("pool/categories/", views.pool_categories, name="pool_categories"),
    path("pool/categories/<str:name>/", views.pool_category_detail, name="pool_category_detail"),
    path("pool/stocks/", views.pool_stocks, name="pool_stocks"),
    path("pool/recent-swings/", views.pool_recent_swings, name="pool_recent_swings"),
    path("pool/stock/<str:ide>/", views.pool_stock, name="pool_stock"),
    path("screen/", views.screen_stocks, name="screen_stocks"),
    path("compare/", views.compare_stocks, name="compare_stocks"),
    path("tech/channel/scan/", views.tech_channel_scan, name="tech_channel_scan"),
    path(
        "tech/independent-strong/scan/",
        views.tech_independent_strong_scan,
        name="tech_independent_strong_scan",
    ),
    path(
        "tech/industry-relative/scan/",
        views.tech_industry_relative_scan,
        name="tech_industry_relative_scan",
    ),
    path("ai/advice/models/", views.ai_advice_models, name="ai_advice_models"),
    path("ai/advice/scan/", views.ai_advice_scan, name="ai_advice_scan"),
    path("ai/advice/confirm/", views.ai_advice_confirm, name="ai_advice_confirm"),
    path("update/config/", views.update_config, name="update_config"),
    path("update/tasks/", views.update_tasks, name="update_tasks"),
    path("update/ratios/", views.update_ratios, name="update_ratios"),
    path("update/reports/", views.update_reports, name="update_reports"),
    path("update/run/", views.update_run, name="update_run"),
    path("update/jobs/", views.update_jobs, name="update_jobs"),
    path("update/jobs/<str:job_id>/", views.update_job, name="update_job"),
]
