from GP_FSA.core.table import Table
from GP_FSA import accounts

tbl_ASSET = Table()
tbl_ASSET.Item([
            accounts['货币资金'].copy().tag_level(1),
                accounts['期末现金及现金等价物余额'].copy().tag_level(2).Color('orchid').tag_Name('其中：现金及现金等价物'),   
                accounts['不属于现金及现金等价物的货币资金'].copy().tag_level(2).Color('orchid').tag_Name('其中：不属于现金及现金等价物的货币资金'),   
                accounts['货币资金比率T非金融'].copy().tag_level(2).Color('green').tag_Name('货币资金比率(非金融)'),   

            accounts['结算备付金'].copy().tag_level(1), 
            accounts['拆出资金'].copy().tag_level(1), 
            accounts['发放贷款及垫款_CA'].copy().tag_level(1), 
            accounts['交易性金融资产'].copy().tag_level(1), 
            accounts['衍生金融资产'].copy().tag_level(1), 
            accounts['应收票据及应收账款_CA'].copy().tag_level(1),
                accounts['应收票据'].copy().tag_level(2),
                accounts['应收账款'].copy().tag_level(2),
                    accounts['应收帐款周转率T非金融'].copy().tag_level(3).Color('green').tag_Name('应收帐款周转率(非金融)'),   
                    accounts['应收帐款周转天数T非金融'].copy().tag_level(3).Color('green').tag_Name('应收帐款周转天数(非金融)'),   

            accounts['应收款项融资'].copy().tag_level(1), 
            accounts['预付款项'].copy().tag_level(1), 
            accounts['应收保费'].copy().tag_level(1),  
            accounts['应收分保账款'].copy().tag_level(1),
            accounts['应收分保合同准备金'].copy().tag_level(1),
            accounts['其他应收款'].copy().tag_level(1),    
                accounts['应收关联公司款'].tag_level(2),
                accounts['应收利息'].copy().tag_level(2),      
                accounts['应收股利'].copy().tag_level(2),        
            accounts['买入返售金融资产'].copy().tag_level(1),   
            accounts['存货'].copy().tag_level(1),           
                    accounts['存货周转率T非金融'].copy().tag_level(3).Color('green').tag_Name('存货周转率(非金融)'),   
                    accounts['存货周转天数T非金融'].copy().tag_level(3).Color('green').tag_Name('存货周转天数(非金融)'),   
                    accounts['存货比率T非金融'].copy().tag_level(3).Color('green').tag_Name('存货比率(非金融)'),   
                
                accounts['消耗性生物资产'].copy().tag_level(2),  
            accounts['合同资产'].copy().tag_level(1),          
            accounts['划分为持有待售的资产'].copy().tag_level(1), 
            accounts['一年内到期的非流动资产'].copy().tag_level(1), 
                accounts['现金到期债务比率TpctT非金融'].copy().tag_level(2).Color('green').tag_Name('现金到期债务比率(非金融)'),   

            accounts['其他流动资产'].copy().tag_level(1),   
        accounts['流动资产合计'].copy().Color('#e5e7eb'),
                accounts['流动资产比率T非金融'].copy().tag_level(2).Color('green').tag_Name('流动资产比率(非金融)'),   

                accounts['流动比率T非金融'].copy().tag_level(2).Color('green').tag_Name('流动比率(非金融)'),   
                accounts['速动比率T非金融'].copy().tag_level(2).Color('green').tag_Name('速动比率(非金融)'),   
                accounts['流动负债比率TpctT非金融'].copy().tag_level(2).Color('green').tag_Name('流动负债比率(非金融)'),   
                accounts['流动资产周转率T非金融'].copy().tag_level(2).Color('green').tag_Name('流动资产周转率(非金融)'),   
                accounts['流动资产周转天数T非金融'].copy().tag_level(2).Color('green').tag_Name('流动资产周转天数(非金融)'),   
            
            
            accounts['发放贷款及垫款_NCA'].copy().tag_level(1),
            accounts['债权投资'].copy().tag_level(1),        
            accounts['其他债权投资'].copy().tag_level(1),  
            accounts['长期应收款'].copy().tag_level(1),  
            accounts['长期股权投资'].copy().tag_level(1),    
            accounts['其他权益工具投资'].copy().tag_level(1),  
            accounts['其他非流动金融资产'].copy().tag_level(1), 
            accounts['投资性房地产'].copy().tag_level(1),   
            accounts['固定资产'].copy().tag_level(1),
                accounts['固定资产周转率T非金融'].copy().tag_level(2).Color('green').tag_Name('固定资产周转率(非金融)'),   
                accounts['固定资产增长率Tpct'].copy().tag_level(2).Color('green').tag_Name('固定资产增长率'),   
                accounts['固定资产比率'].copy().tag_level(2).Color('green').tag_Name('固定资产比率'),   
                   
            accounts['在建工程'].copy().tag_level(1),      
            accounts['工程物资'].copy().tag_level(1),        
            accounts['固定资产清理'].copy().tag_level(1),    
            accounts['生产性生物资产'].copy().tag_level(1),   
            accounts['油气资产'].copy().tag_level(1),         
            accounts['使用权资产'].copy().tag_level(1),       
            accounts['无形资产'].copy().tag_level(1),       
            accounts['开发支出'].copy().tag_level(1),          
            accounts['商誉'].copy().tag_level(1),             
            accounts['长期待摊费用'].copy().tag_level(1),      
            accounts['递延所得税资产'].copy().tag_level(1),    
            accounts['可供出售金融资产'].copy().tag_level(1),  
            accounts['持有至到期投资'].copy().tag_level(1),    
            accounts['其他非流动资产'].copy().tag_level(1),     
        accounts['非流动资产合计'].copy().Color('#e5e7eb'),
                accounts['非流动负债比率TpctT非金融'].copy().tag_level(2).Color('green').tag_Name('非流动负债比率(非金融)'),   

    accounts['资产总计'].copy().Color('red'),
                accounts['有形资产净值债务率Tpct'].copy().tag_level(2).Color('green').tag_Name('有形资产净值债务率%'),   
                accounts['有形资产_净债务Tpct'].copy().tag_level(2).Color('green').tag_Name('有形资产/净债务%'),   
                
                accounts['总资产周转率T非金融'].copy().tag_level(2).Color('green').tag_Name('总资产周转率(非金融)'),   
                accounts['总资产周转天数T非金融'].copy().tag_level(2).Color('green').tag_Name('总资产周转天数(非金融)'),   
                accounts['总资产增长率Tpct'].copy().tag_level(2).Color('green').tag_Name('总资产增长率'),   
                accounts['总资产报酬率'].copy().tag_level(2).Color('green').tag_Name('总资产报酬率'),   
                accounts['资产负债率Tpct'].copy().tag_level(2).Color('green').tag_Name('资产负债率'),   
                accounts['全部资产现金回收率'].copy().tag_level(2).Color('green').tag_Name('全部资产现金回收率%'),   
])


tbl_流动资产 = Table()
tbl_流动资产.Item([
    accounts['货币资金'],
    accounts['结算备付金'],
    accounts['拆出资金'],
    accounts['发放贷款及垫款_CA'],
    accounts['交易性金融资产'],
    accounts['衍生金融资产'],
    accounts['应收票据及应收账款_CA'],
        accounts['应收票据'].copy().tag_level(1),
        accounts['应收账款'].copy().tag_level(1),
    accounts['应收款项融资'],
    accounts['预付款项'],
    accounts['应收保费'],
    accounts['应收分保账款'],
    accounts['应收分保合同准备金'],
    accounts['其他应收款'],
        accounts['应收关联公司款'].tag_level(1),
        accounts['应收利息'].copy().tag_level(1),      
        accounts['应收股利'].copy().tag_level(1),        
    accounts['买入返售金融资产'],
    accounts['存货'],
        accounts['消耗性生物资产'].copy().tag_level(1),  
    accounts['合同资产'],
    accounts['划分为持有待售的资产'],
    accounts['一年内到期的非流动资产'],
    accounts['其他流动资产'],
    accounts['流动资产合计'].copy().Color('#e5e7eb'),
])

tbl_非流动资产 = Table()
tbl_非流动资产.Item([
    accounts['发放贷款及垫款_NCA'],
    accounts['债权投资'],
    accounts['其他债权投资'],
    accounts['长期应收款'],
    accounts['长期股权投资'],
    accounts['其他权益工具投资'],
    accounts['其他非流动金融资产'],
    accounts['投资性房地产'],
    accounts['固定资产'],
    accounts['在建工程'],
    accounts['工程物资'],
    accounts['固定资产清理'],
    accounts['生产性生物资产'],
    accounts['油气资产'],
    accounts['使用权资产'],
    accounts['无形资产'],
    accounts['开发支出'],
    accounts['商誉'],
    accounts['长期待摊费用'],
    accounts['递延所得税资产'],
    accounts['可供出售金融资产'],
    accounts['持有至到期投资'],
    accounts['其他非流动资产'],
    accounts['非流动资产合计'].copy().Color('#e5e7eb')
])

tbl_LIAB_EQU = Table().Item([
        accounts['短期借款'].copy().tag_level(1),
        accounts['向中央银行借款'].copy().tag_level(1),
        accounts['吸收存款及同业存放'].copy().tag_level(1),
        accounts['拆入资金'].copy().tag_level(1),
        accounts['交易性金融负债'].copy().tag_level(1),
        accounts['衍生金融负债'].copy().tag_level(1),
        accounts['应付票据及应付账款_CL'].copy().tag_level(1),
            accounts['应付票据'].copy().tag_level(2),
            accounts['应付账款'].copy().tag_level(2),
        accounts['预收款项'].copy().tag_level(1),
        accounts['合同负债'].copy().tag_level(1),
        accounts['卖出回购金融资产款'].copy().tag_level(1),
        accounts['代理买卖证券款'].copy().tag_level(1),
        accounts['代理承销证券款'].copy().tag_level(1),
        accounts['应付职工薪酬'].copy().tag_level(1),
        accounts['应交税费'].copy().tag_level(1),
        accounts['其他应付款'].copy().tag_level(1),
        accounts['应付手续费及佣金'].copy().tag_level(1),
        accounts['应付分保账款'].copy().tag_level(1),
        accounts['划分为持有待售的负债'].copy().tag_level(1),
        accounts['一年内到期的非流动负债'].copy().tag_level(1),
        accounts['应付关联公司款'].copy().tag_level(1),
        accounts['其他流动负债'].copy().tag_level(1),
    accounts['流动负债合计'].copy().Color('#e5e7eb'),

        accounts['保险合同准备金'].copy().tag_level(1),
        accounts['长期借款'].copy().tag_level(1),
        accounts['应付债券'].copy().tag_level(1),
            accounts['应付债券_优先股'].copy().tag_level(2),
            accounts['应付债券_永续债'].copy().tag_level(2),
        accounts['租赁负债'].copy().tag_level(1),
        accounts['长期应付款'].copy().tag_level(1),
        accounts['长期应付职工薪酬'].copy().tag_level(1),
        accounts['预计负债'].copy().tag_level(1),
        accounts['递延收益_NCL'].copy().tag_level(1),
        accounts['递延所得税负债'].copy().tag_level(1),
        accounts['其他非流动负债'].copy().tag_level(1),
        accounts['专项应付款'].copy().tag_level(1),
    accounts['非流动负债合计'].copy().Color('#e5e7eb'),

accounts['负债合计'].copy().Color('red'),
        accounts['有形资产_负债合计Tpct'].copy().tag_level(3).Color('green').tag_Name('有形资产_负债合计%'),   
        accounts['资产负债率Tpct'].copy().tag_level(3).Color('green').tag_Name('资产负债率%'),   
        accounts['负债结构比T非金融'].copy().tag_level(3).Color('green').tag_Name('负债结构比(非金融)'),   


        accounts['总股本'].copy().Color('green').copy().tag_level(2),
        accounts['实收资本'].copy().tag_level(1),
        accounts['其他权益工具_EQ'].copy().tag_level(1),
            accounts['优先股_EQ'].copy().tag_level(2),
            accounts['永续债_EQ'].copy().tag_level(2),
        accounts['资本公积'].copy().tag_level(1),
        accounts['库存股'].copy().tag_level(1),
        accounts['盈余公积'].copy().tag_level(1),
        accounts['专项储备'].copy().tag_level(1),
        accounts['一般风险准备_金融类'].copy().tag_level(1),
        accounts['未分配利润'].copy().tag_level(1),
        accounts['其他综合收益_EQ'].copy().tag_level(1),
        accounts['外币报表折算价差'].copy().tag_level(1),
        accounts['非正常经营项目收益调整'].copy().tag_level(1),      
    accounts['归属于母公司股东权益总计'].copy().Color('#e5e7eb'),
            accounts['归属于母公司股东权益_全部投入资本Tpct'].copy().tag_level(2).Color('green').tag_Name('归属于母公司股东权益/全部投入资本 %'),

    accounts['少数股东权益_EQ'].copy().Color('#e5e7eb'),
    accounts['股东权益合计'].copy().Color('red'),
            accounts['股东权益周转率T非金融'].copy().tag_level(3).Color('green').tag_Name('股东权益周转率(非金融)'),   

            accounts['每股净资产'].copy().tag_level(2).Color('green'),
            accounts['每股资本公积金'].copy().tag_level(2).Color('green'),
            accounts['权益乘数Tpct'].copy().tag_level(2).Color('green').tag_Name('权益乘数%'),
            accounts['股东的权益_负债合计Tpct'].copy().tag_level(2).Color('green').tag_Name('股东权益/负债'),
            accounts['股东权益周转率T非金融'].copy().tag_level(2).Color('green').tag_Name('股东权益周转率'),
            accounts['负债结构比T非金融'].copy().tag_level(2).Color('green').tag_Name('负债结构比'),
            accounts['股东的权益_带息债务Tpct'].copy().tag_level(2).Color('green').tag_Name('股东权益/带息债务 %'),
accounts['负债和股东权益合计'].copy().Color('red')
])



tbl_流动负债 = Table().Item([
    accounts['短期借款'],
    accounts['向中央银行借款'],
    accounts['吸收存款及同业存放'],
    accounts['拆入资金'],
    accounts['交易性金融负债'],
    accounts['衍生金融负债'],
    accounts['应付票据及应付账款_CL'],
        accounts['应付票据'].copy().tag_level(1),
        accounts['应付账款'].copy().tag_level(1),
    accounts['预收款项'],
    accounts['合同负债'],
    accounts['卖出回购金融资产款'],
    accounts['代理买卖证券款'],
    accounts['代理承销证券款'],
    accounts['应付职工薪酬'],
    accounts['应交税费'],
    accounts['其他应付款'],
    accounts['应付手续费及佣金'],
    accounts['应付分保账款'],
    accounts['划分为持有待售的负债'],
    accounts['一年内到期的非流动负债'],
    accounts['应付关联公司款'],
    accounts['其他流动负债'],
accounts['流动负债合计'].copy().Color('#e5e7eb')
])


tbl_非流动负债 = Table().Item([
    accounts['保险合同准备金'],
    accounts['长期借款'],
    accounts['应付债券'],
        accounts['应付债券_优先股'].copy().tag_level(1),
        accounts['应付债券_永续债'].copy().tag_level(1),
    accounts['租赁负债'],
    accounts['长期应付款'],
    accounts['长期应付职工薪酬'],
    accounts['预计负债'],
    accounts['递延收益_NCL'],
    accounts['递延所得税负债'],
    accounts['其他非流动负债'],
    accounts['专项应付款'],
accounts['非流动负债合计'].copy().Color('#e5e7eb')
])



tbl_股东权益 = Table().Item([
    accounts['总股本'].copy().Color('green'),

    accounts['实收资本'],
    accounts['其他权益工具_EQ'],
        accounts['优先股_EQ'].copy().tag_level(1),
        accounts['永续债_EQ'].copy().tag_level(1),
    accounts['资本公积'],
    accounts['库存股'],
    accounts['盈余公积'],
    accounts['专项储备'],
    accounts['一般风险准备_金融类'],
    accounts['未分配利润'],
    accounts['其他综合收益_EQ'],
    accounts['外币报表折算价差'],
    accounts['非正常经营项目收益调整'],
    accounts['归属于母公司股东权益总计'].copy().Color('#e5e7eb'),
    accounts['少数股东权益_EQ'].copy().Color('#e5e7eb'),
    accounts['股东权益合计'].copy().Color('#e5e7eb'),
        accounts['每股净资产'].copy().tag_level(1).Color('green'),
        accounts['每股资本公积金'].copy().tag_level(1).Color('green'),
        accounts['权益乘数Tpct'].copy().tag_level(1).Color('green').tag_Name('权益乘数%'),
        accounts['股东的权益_负债合计Tpct'].copy().tag_level(1).Color('green').tag_Name('股东权益/负债'),
        accounts['股东权益周转率T非金融'].copy().tag_level(1).Color('green').tag_Name('股东权益周转率'),
        accounts['负债结构比T非金融'].copy().tag_level(1).Color('green').tag_Name('负债结构比'),
        accounts['归属于母公司股东权益_全部投入资本Tpct'].copy().tag_level(1).Color('green').tag_Name('归属于母公司股东权益/全部投入资本 %'),
        accounts['股东的权益_带息债务Tpct'].copy().tag_level(1).Color('green').tag_Name('股东权益/带息债务 %'),
        
        
        # 股东权益周转率T非金融'].copy().tag_level(1).Color('green'),

])
