from GP_FSA.core.table import Table
from GP_FSA import accounts

tbl_IS = Table()
tbl_IS.Item([
    accounts['营业总收入'].copy().Color('#e5e7eb').tag_Name('一、营业总收入'), 
        accounts['营业总收入_营业收入'].copy().tag_level(1).tag_Name('营业收入'),
        accounts['营业总收入_利息收入'].copy().tag_level(1).tag_Name('利息收入'),
        accounts['营业总收入_已赚保费'].copy().tag_level(1).tag_Name('已赚保费'),
        accounts['营业总收入_手续费及佣金收入'].copy().tag_level(1).tag_Name('手续费及佣金收入'),
    accounts['营业总成本'].copy().Color('#e5e7eb').tag_Name('二、营业总成本'), 
        accounts['营业成本'].copy().tag_level(1),
        accounts['利息支出'].copy().tag_level(1),
        accounts['手续费及佣金支出'].copy().tag_level(1),
        accounts['退保金'].copy().tag_level(1),
        accounts['赔付支出净额'].copy().tag_level(1),
        accounts['提取保险合同准备金净额'].copy().tag_level(1),
        accounts['保单红利支出'].copy().tag_level(1),
        accounts['分保费用'].copy().tag_level(1),
        accounts['营业税金及附加'].copy().tag_level(1),
        accounts['销售费用'].copy().tag_level(1),
        accounts['管理费用'].copy().tag_level(1),
        accounts['研发费用_IS'].copy().tag_level(1),
        accounts['勘探费用'].copy().tag_level(1),
        accounts['财务费用_IS'].copy().tag_level(1),
            accounts['财务费用_利息费用'].copy().tag_level(2).tag_Name('其中：利息费用'),
            accounts['财务费用_利息收入'].copy().tag_level(2).tag_Name('其中：利息收入'),
        accounts['其他收益_IS'].copy().tag_level(1).tag_Name('加：其他收益'),
        accounts['投资收益'].copy().tag_level(1),
            accounts['投资收益_对联营企业和合营企业的投资收益'].copy().tag_level(2).tag_Name('其中：对联营企业和合营企业的投资收益'),
        accounts['汇兑收益'].copy().tag_level(1),
        accounts['净敞口套期收益'].copy().tag_level(1),
        accounts['信用减值损失2019'].copy().tag_level(1),
        accounts['资产减值损失2019'].copy().tag_level(1),
        accounts['资产处置收益_IS'].copy().tag_level(1),
        accounts['补贴收入'].copy().tag_level(1),
        accounts['影响营业利润的其他科目'].copy().tag_level(1),

    accounts['营业利润'].copy().Color('#e5e7eb').tag_Name('三、营业利润'), 
        accounts['营业外收入'].copy().tag_level(1).tag_Name('加：营业外收入'),
        accounts['营业外支出'].copy().tag_level(1).tag_Name('减：营业外支出'),
        accounts['影响利润总额的其他科目'].copy().tag_level(1),
    accounts['利润总额'].copy().Color('#e5e7eb').tag_Name('四、利润总额'),
        accounts['所得税'].copy().tag_level(1).tag_Name('减：所得税'),
        accounts['影响净利润的其他科目'].copy().tag_level(1).tag_Name('加：影响净利润的其他科目'),
    accounts['净利润'].copy().Color('#e5e7eb').tag_Name('五、净利润'),
        accounts['持续经营净利润'].copy().tag_level(1).tag_Name('1.持续经营净利润'),
        accounts['终止经营净利润'].copy().tag_level(1).tag_Name('2.终止经营净利润'),
        accounts['归属于母公司股东的净利润'].copy().tag_level(1).tag_Name('1.归属于母公司股东的净利润'),
        accounts['少数股东损益'].copy().tag_level(1).tag_Name('2.少数股东损益'),
        accounts['归属于母公司股东的其他综合收益的税后净额'].copy().tag_level(1).tag_Name('1.归属于母公司股东的其他综合收益的税后净额'),
        accounts['归属于少数股东的其他综合收益的税后净额'].copy().tag_level(1).tag_Name('2.归属于少数股东的其他综合收益的税后净额'),
    accounts['综合收益总额'].copy().Color('#e5e7eb').tag_Name('七、综合收益总额'),
        accounts['归属于母公司综合收益'].copy().tag_level(1).tag_Name('1.归属于母公司综合收益'),
        accounts['归属于少数股东综合收益'].copy().tag_level(1).tag_Name('2.归属于少数股东综合收益'),
    accounts['基本每股收益'].copy().tag_level(1).Color('green'),
    accounts['扣除非经常性损益每股收益'].copy().tag_level(1).Color('green'),
        accounts['扣非每股收益同比Tpct'].copy().tag_level(2).Color('green').tag_Name('扣非每股收益同比%'),
    accounts['稀释每股收益'].copy().tag_level(1).Color('green'),
    accounts['每股未分配利润'].copy().tag_level(1).Color('green'),
    accounts['总股本'].copy().Color('green').tag_Name('八、总股本'),
    accounts['净资产收益率'].copy().tag_level(1).Color('green').tag_Name('净资产收益率 %'),
    accounts['利息保障倍数T非金融'].copy().tag_level(1).Color('green').tag_Name('利息保障倍数(非金融)'),
    accounts['存货周转率T非金融'].copy().tag_level(1).Color('green').tag_Name('存货周转率(非金融)'),
    accounts['运营资金周转率T非金融'].copy().tag_level(1).Color('green').tag_Name('运营资金周转率(非金融)'),
    accounts['总资产周转率T非金融'].copy().tag_level(1).Color('green').tag_Name('总资产周转率(非金融)'),
    accounts['固定资产周转率T非金融'].copy().tag_level(1).Color('green').tag_Name('固定资产周转率(非金融)'),
    accounts['应收帐款周转天数T非金融'].copy().tag_level(1).Color('green').tag_Name('应收帐款周转天数(非金融)'),
    accounts['存货周转天数T非金融'].copy().tag_level(1).Color('green').tag_Name('存货周转天数(非金融)'),
    accounts['流动资产周转率T非金融'].copy().tag_level(1).Color('green').tag_Name('流动资产周转率(非金融)'),
    accounts['流动资产周转天数T非金融'].copy().tag_level(1).Color('green').tag_Name('流动资产周转天数(非金融)'),
    accounts['总资产周转天数T非金融'].copy().tag_level(1).Color('green').tag_Name('总资产周转天数(非金融)'),
    accounts['营业收入增长率Tpct'].copy().tag_level(1).Color('green').tag_Name('营业收入增长率 %'),
    accounts['净利润增长率Tpct'].copy().tag_level(1).Color('green').tag_Name('净利润增长率 %'),
    accounts['净资产增长率Tpct'].copy().tag_level(1).Color('green').tag_Name('净资产增长率 %'),
    accounts['固定资产增长率Tpct'].copy().tag_level(1).Color('green').tag_Name('固定资产增长率 %'),
    accounts['总资产增长率Tpct'].copy().tag_level(1).Color('green').tag_Name('总资产增长率 %'),
    accounts['营业利润增长率Tpct'].copy().tag_level(1).Color('red').tag_Name('营业利润增长率 %'),

    accounts['扣非净利润同比Tpct'].copy().tag_level(1).Color('green').tag_Name('扣非净利润同比 %'),
    accounts['成本费用利润率Tpct'].copy().tag_level(1).Color('green').tag_Name('成本费用利润率 %'),
    accounts['营业利润率T非金融'].copy().tag_level(1).Color('green').tag_Name('营业利润率(非金融)'),
    accounts['营业税金率T非金融'].copy().tag_level(1).Color('green').tag_Name('营业税金率(非金融)'),
    accounts['营业成本率T非金融'].copy().tag_level(1).Color('green').tag_Name('营业成本率(非金融)'),
    accounts['投资收益率'].copy().tag_level(1).Color('green').tag_Name('投资收益率'),
    accounts['销售净利率Tpct'].copy().tag_level(1).Color('green').tag_Name('销售净利率 %'),
    accounts['总资产报酬率'].copy().tag_level(1).Color('green').tag_Name('总资产报酬率'),
    accounts['净利润率T非金融'].copy().tag_level(1).Color('green').tag_Name('净利润率(非金融)'),
    accounts['销售毛利率TpctT非金融'].copy().tag_level(1).Color('green').tag_Name('销售毛利率(非金融)'),
    accounts['三费比重T非金融'].copy().tag_level(1).Color('green').tag_Name('三费比重(非金融)'),
    accounts['管理费用率T非金融'].copy().tag_level(1).Color('green').tag_Name('管理费用率(非金融)'),
    accounts['财务费用率T非金融'].copy().tag_level(1).Color('green').tag_Name('财务费用率(非金融)'),
    accounts['扣除非经常性损益后的净利润'].copy().tag_level(1).Color('green').tag_Name('扣除非经常性损益后的净利润'),
    accounts['息税前利润_EBIT'].copy().tag_level(1).Color('green').tag_Name('EBIT'),
    accounts['息税折旧摊销前利润_EBITDA'].copy().tag_level(1).Color('green').tag_Name('EBITDA'),
    accounts['EBITDA_营业总收入TpctT非金融'].copy().tag_level(1).Color('green').tag_Name('EBITDA/营业总收入(非金融)'),
    accounts['营业收入现金含量TpctT非金融'].copy().tag_level(1).Color('green').tag_Name('营业收入现金含量%(非金融)'),
    accounts['经营活动产生的现金流量净额_经营活动净收益Tpct'].copy().tag_level(1).Color('green').tag_Name('经营活动产生的现金流量净额/经营活动净收益'),
    accounts['销售商品提供劳务收到的现金_营业收入Tpct'].copy().tag_level(1).Color('green').tag_Name('销售商品提供劳务收到的现金/营业收入'),
    accounts['经营活动产生的现金流量净额_营业收入'].copy().tag_level(1).Color('green').tag_Name('经营活动产生的现金流量净额/营业收入'),
    accounts['资本支出_折旧和摊销'].copy().tag_level(1).Color('green').tag_Name('资本支出/折旧和摊销'),

])
