"""Industry profit growth metrics and yearly aggregation."""

from .metrics import (
    CAGR_PERIOD_3,
    CAGR_PERIOD_5,
    MIN_COMPANY_COUNT_CONFIDENT,
    STATUS_BASE_PROFIT_NON_POSITIVE,
    STATUS_LOSS_TO_LOSS,
    STATUS_PROFITABLE,
    STATUS_PROFIT_TO_LOSS,
    STATUS_TURNED_PROFITABLE,
    added_profit,
    build_industry_metrics,
    calc_cagr,
    calc_growth_confidence,
    calc_growth_score,
    calc_growth_stability,
    calc_yoy_growth,
    contribution_shares,
    industry_profit_sum,
    percentile_ranks,
    rank_industries,
    safe_float,
    sort_key_for_period,
)

__all__ = [
    "CAGR_PERIOD_3",
    "CAGR_PERIOD_5",
    "MIN_COMPANY_COUNT_CONFIDENT",
    "STATUS_BASE_PROFIT_NON_POSITIVE",
    "STATUS_LOSS_TO_LOSS",
    "STATUS_PROFITABLE",
    "STATUS_PROFIT_TO_LOSS",
    "STATUS_TURNED_PROFITABLE",
    "added_profit",
    "build_industry_metrics",
    "calc_cagr",
    "calc_growth_confidence",
    "calc_growth_score",
    "calc_growth_stability",
    "calc_yoy_growth",
    "contribution_shares",
    "industry_profit_sum",
    "percentile_ranks",
    "rank_industries",
    "safe_float",
    "sort_key_for_period",
]
